### ISSUE TITLE
make backup频繁fail

### ISSUE THREAD

**Issue by BlackPotatooooo** [PKUNoRun/PKUNoRun#11]
最开始的fail是adb和安卓版本不同导致的，在[这里](https://android.stackexchange.com/questions/83080/adb-backup-creates-0-byte-file-prompts-for-current-backup-password-even-though/) 找到了解决方式，修改makefile中的`adb backup -nosystem -noapk -f apps.ab cn.edu.pku.pkurunner`为`adb backup "cn.edu.pku.pkurunner" -nosystem -noapk -f apps.ab`。
然而执行make backup的时候还是报错，想问一下怎么解决：
`z@DESKTOP-84SEQVD:~/PKUNoRun$ make backup
rm -fr apps/ apps.tar apps.list apps.ab
#adb backup -nosystem -noapk -f apps.ab cn.edu.pku.pkurunner
adb backup "cn.edu.pku.pkurunner" -nosystem -noapk -f apps.ab
Now unlock your device and confirm the backup operation.
java -jar ./abe.jar unpack apps.ab apps.tar

49%
1024 bytes written to apps.tar.
tar tf apps.tar | grep -F "cn.edu.pku.pkurunner" | grep -v "wal" | grep -v "shm" > apps.list
makefile:47: recipe for target 'backup' failed
make: *** [backup] Error 1`

**Comment by baker221** [comment]
同样遇到这个问题，成功一次之后再也无法成功

**Comment by HamiltonHuaji** [comment]
其实我也不知道...看起来是abe.jar的问题(1024 bytes大小的apps.tar肯定是损坏了的), 但是这玩意不是我写的, 给[原作者](https://github.com/nelenkov/android-backup-extractor)提issue吧qwq, 或者你自己从原作者那里下载最新的release换掉本repo自带的abe.jar试试?

**Comment by HamiltonHuaji** [comment]
用二进制编辑器打开apps.ab之后发现这玩意里啥也没有...所以结论是adb backup没有备份出真实数据, 错怪abe.jar了

**Comment by HamiltonHuaji** [comment]
尝试在备份时输入非空密码, 就成功了.

**Comment by j1ngYS** [comment]
> 尝试在备份时输入非空密码, 就成功了.

请问下密码长度的规定是怎样的？
我的报错信息如下：

Password: 
Exception in thread "main" java.lang.RuntimeException: java.security.InvalidKeyException: Illegal key size
	at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:233)
	at org.nick.abe.Main.main(Main.java:40)
Caused by: java.security.InvalidKeyException: Illegal key size
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1039)
	at javax.crypto.Cipher.implInit(Cipher.java:805)
	at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
	at javax.crypto.Cipher.init(Cipher.java:1396)
	at javax.crypto.Cipher.init(Cipher.java:1327)
	at org.nick.abe.AndroidBackup.extractAsTar(AndroidBackup.java:128)
	... 1 more
make: *** [makefile:49：backup] 错误 1

**Comment by HamiltonHuaji** [comment]
我用过`114514`作为密码, 成功了... 所以6位密码肯定ok.
反正备份用完即可删除, 随便设个密码就行.

**Comment by j1ngYS** [comment]
> 我用过`114514`作为密码, 成功了... 所以6位密码肯定ok.
> 反正备份用完即可删除, 随便设个密码就行.

感谢回复，不过我试了0-9位的数字密码都不行，报错信息一样（准备跑路windows环境下试试了

**Comment by baker221** [comment]
> > 我用过`114514`作为密码, 成功了... 所以6位密码肯定ok.
> > 反正备份用完即可删除, 随便设个密码就行.
> 
> 感谢回复，不过我试了0-9位的数字密码都不行，报错信息一样（准备跑路windows环境下试试了

可以试试在 backup 时候打开着 PKURunner 的界面。我之前在手机桌面备份报错，在软件打开的界面备份就成功了。系统 macOS

**Comment by j1ngYS** [comment]
> > > 我用过`114514`作为密码, 成功了... 所以6位密码肯定ok.
> > > 反正备份用完即可删除, 随便设个密码就行.
> > 
> > 
> > 感谢回复，不过我试了0-9位的数字密码都不行，报错信息一样（准备跑路windows环境下试试了
> 
> 可以试试在 backup 时候打开着 PKURunner 的界面。我之前在手机桌面备份报错，在软件打开的界面备份就成功了。系统 macOS

好的，谢谢xd，我试试

**Comment by DOFYPXY** [comment]
> 同样遇到这个问题，试了4-10位密码，尝试打开PKUrunner界面，均不成功。用的是wsl 错误代码如下 rm -fr apps/ apps.tar apps.list apps.ab adb backup -nosystem -noapk -f apps.ab cn.edu.pku.pkurunner Now unlock your device and confirm the backup operation... java -jar ./abe.jar unpack apps.ab apps.tar This backup is encrypted, please provide the password Password: Calculated MK checksum (use UTF-8: true): 3CC69BB4EA57F2B2D553AB6BBC69E7E427548E74474D20CA278741AD7EA3E911 3% 1024 bytes written to apps.tar. tar tf apps.tar | grep -F "cn.edu.pku.pkurunner" | grep -v "wal" | grep -v "shm" > apps.list make: *** [makefile:50：backup] 错误 1

同样遇到了这个问题

**Comment by DOFYPXY** [comment]
> 同样遇到这个问题，试了4-10位密码，尝试打开PKUrunner界面，均不成功。用的是wsl 错误代码如下 rm -fr apps/ apps.tar apps.list apps.ab adb backup -nosystem -noapk -f apps.ab cn.edu.pku.pkurunner Now unlock your device and confirm the backup operation... java -jar ./abe.jar unpack apps.ab apps.tar This backup is encrypted, please provide the password Password: Calculated MK checksum (use UTF-8: true): 3CC69BB4EA57F2B2D553AB6BBC69E7E427548E74474D20CA278741AD7EA3E911 3% 1024 bytes written to apps.tar. tar tf apps.tar | grep -F "cn.edu.pku.pkurunner" | grep -v "wal" | grep -v "shm" > apps.list make: *** [makefile:50：backup] 错误 1

遇到了完全一样的问题 我用的是ubuntu

**Comment by xiaotianxt** [comment]
> > > > 我用过`114514`作为密码, 成功了... 所以6位密码肯定ok.
> > > > 反正备份用完即可删除, 随便设个密码就行.
> > > 
> > > 
> > > 感谢回复，不过我试了0-9位的数字密码都不行，报错信息一样（准备跑路windows环境下试试了
> > 
> > 
> > 可以试试在 backup 时候打开着 PKURunner 的界面。我之前在手机桌面备份报错，在软件打开的界面备份就成功了。系统 macOS
> 
> 好的，谢谢xd，我试试

完全一样的问题，macOS有解决的hxd吗？

我一年前用的MIUI还是没问题的，今年换成了lineageOS竟然刷不了。。。

**Comment by DOFYPXY** [comment]
> 唔，我好像整明白了，目前最新的版本对我来说是不能进行adb backup的（会出现那个1024 bytes的错误），不过某个历史版本可以，比如github上面的版本，缺点是每次打开都会提醒版本更新，只需要ignore，然后回桌面，重新进入就行了。

请问你指的是pkurunner的历史版本吗

**Comment by xiaotianxt** [comment]
> 请问你指的是pkurunner的历史版本吗

对的，就是软件没法跑步了只能刷里程😅

**Comment by DOFYPXY** [comment]
> > 所以说是老版本刷的数据没法上传到现在版本的pkurunner了吗2333333
> 
> 我不理解，反正能用就行了

哦原来你的意思是能用的，那方便给一个旧版本的下载链接吗

**Comment by xiaotianxt** [comment]
> 哦原来你的意思是能用的，那方便给一个旧版本的下载链接吗

奶奶的，今天又失败了，我无语了

**Comment by xiazhongyv** [comment]
WSL遇到了同样的问题，所以大伙解决这个问题了吗
