### ISSUE TITLE
unable to open database file求助

### ISSUE THREAD

**Issue by Harvin-hmYang** [PKUNoRun/PKUNoRun#9]
手机通过adb连接至linux虚拟机后，在内部存储-PKUNoRun-master下执行python3 generator/generator.py ......命令报错，提示Traceback (most recent call last):
  File "generator/generator.py", line 21, in <module>
    db = sqlite3.connect(args.db)
sqlite3.OperationalError: unable to open database file
求助怎么解决
![image](https://user-images.githubusercontent.com/61138284/114335894-50e16500-9b80-11eb-81b3-78a61baa5ffe.png)

**Comment by HamiltonHuaji** [comment]
请检查apps/cn.edu.pku.pkurunner/f/data.db是否存在. 如果存在, 尝试使用sqlitebrowser等工具打开确认里面有内容(有user表). 如果不存在, 尝试如下步骤:

- 清除PKURunner的数据, 重新登录
- 完全退出PKURunner
- 重新执行README.md中描述的步骤

第一次登录后PKURunner不会立即写入数据库, 因此需要待其退出后再执行make backup. 目前我只能想到以上原因.

**Comment by vnindavb** [comment]
> 手机通过adb连接至linux虚拟机后，在内部存储-PKUNoRun-master下执行python3 generator/generator.py ......命令报错，提示Traceback (most recent call last):
> File "generator/generator.py", line 21, in
> db = sqlite3.connect(args.db)
> sqlite3.OperationalError: unable to open database file
> 求助怎么解决
> ![image](https://user-images.githubusercontent.com/61138284/114335894-50e16500-9b80-11eb-81b3-78a61baa5ffe.png)

遇到同样的问题,请问解决了么

**Comment by vnindavb** [comment]
> 请检查apps/cn.edu.pku.pkurunner/f/data.db是否存在. 如果存在, 尝试使用sqlitebrowser等工具打开确认里面有内容(有user表). 如果不存在, 尝试如下步骤:
> 
> * 清除PKURunner的数据, 重新登录
> * 完全退出PKURunner
> * 重新执行README.md中描述的步骤
> 
> 第一次登录后PKURunner不会立即写入数据库, 因此需要待其退出后再执行make backup. 目前我只能想到以上原因.

请问这个apps/cn.edu.pku.pkurunner/f/data.db是应该在我的手机上面找么(抱歉,我太小白了..
